### ISSUE TITLE
Create About Me Section

### ISSUE THREAD

**Issue by gp3man** [gp3man/TonyThymeBlog_next_v1#1]
- [x] Add fields into contentful
- [x] create page
- [x] style

**Comment by gp3man** [comment]
- [x] Write Bio for page @brny09

**Comment by brny09** [comment]
What’s up y'all, my name is William ‘Tony Thyme’ Barney and I’m glad you’re here! I originally hail from the South Side of Chicago, Englewood to be exact! It was here where I first made the ridiculous statement to my mother that I didn’t need to learn how to cook because my wife would do it for me. Luckily for me, my mom took that personally and gave me the skills he needed to begin his journey. Especially since my wife doesn’t like to cook (karma be karming)!

Inspired by foods I would experience in various restaurants and in my world travels, I taught myself how to cook the old fashioned way, by failing forward!

I love elevated food experiences and taking comfort foods and putting a bougie spin on them. I truly believe that no one deserves to eat boring food, and I aim to put a stop to it, plate by plate!
